
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path.cwd()  # Gets the current working directory
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0" 

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("980x653")
window.configure(bg = "#293E73")


canvas = Canvas(
    window,
    bg = "#293E73",
    height = 653,
    width = 980,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    38.0,
    980.0,
    155.0,
    fill="#D0D0D0",
    outline="")

canvas.create_text(
    465.0,
    57.0,
    anchor="nw",
    text="G-ZONE",
    fill="#0F1A36",
    font=("Cairo Black", 40 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    426.0,
    97.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,        activebackground="#293E73",

    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=72.0,
    y=570.0,
    width=189.0,
    height=44.0
)

button_image_hover_1 = PhotoImage(
    file=relative_to_assets("button_hover_1.png"))

def button_1_hover(e):
    button_1.config(
        image=button_image_hover_1
    )
def button_1_leave(e):
    button_1.config(
        image=button_image_1
    )

button_1.bind('<Enter>', button_1_hover)
button_1.bind('<Leave>', button_1_leave)


button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,        activebackground="#293E73",

    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=474.0,
    y=570.0,
    width=151.0,
    height=44.0
)

button_image_hover_2 = PhotoImage(
    file=relative_to_assets("button_hover_2.png"))

def button_2_hover(e):
    button_2.config(
        image=button_image_hover_2
    )
def button_2_leave(e):
    button_2.config(
        image=button_image_2
    )

button_2.bind('<Enter>', button_2_hover)
button_2.bind('<Leave>', button_2_leave)


button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,        activebackground="#293E73",

    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=292.0,
    y=570.0,
    width=151.0,
    height=44.0
)

button_image_hover_3 = PhotoImage(
    file=relative_to_assets("button_hover_3.png"))

def button_3_hover(e):
    button_3.config(
        image=button_image_hover_3
    )
def button_3_leave(e):
    button_3.config(
        image=button_image_3
    )

button_3.bind('<Enter>', button_3_hover)
button_3.bind('<Leave>', button_3_leave)


button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,        activebackground="#293E73",

    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=656.0,
    y=570.0,
    width=151.0,
    height=44.0
)

button_image_hover_4 = PhotoImage(
    file=relative_to_assets("button_hover_4.png"))

def button_4_hover(e):
    button_4.config(
        image=button_image_hover_4
    )
def button_4_leave(e):
    button_4.config(
        image=button_image_4
    )

button_4.bind('<Enter>', button_4_hover)
button_4.bind('<Leave>', button_4_leave)


button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,        activebackground="#293E73",

    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=888.0,
    y=570.0,
    width=44.0,
    height=44.0
)

button_image_hover_5 = PhotoImage(
    file=relative_to_assets("button_hover_5.png"))

def button_5_hover(e):
    button_5.config(
        image=button_image_hover_5
    )
def button_5_leave(e):
    button_5.config(
        image=button_image_5
    )

button_5.bind('<Enter>', button_5_hover)
button_5.bind('<Leave>', button_5_leave)


canvas.create_rectangle(
    72.0,
    232.0,
    932.0,
    321.0,
    fill="#0F1C3C",
    outline="")

canvas.create_rectangle(
    72.0,
    297.0,
    932.0,
    529.0,
    fill="#101D3D",
    outline="")

canvas.create_rectangle(
    72.0,
    297.0,
    932.0,
    529.0,
    fill="#D9D9D9",
    outline="")

appname = canvas.create_text(
    374.0,
    234.0,
    anchor="nw",
    text="Current AppName",
    fill="#D9D9D9",
    font=("Cairo Black", 32 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    980.0,
    35.0,
    fill="#D9D9D9",
    outline="")

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,        
    activebackground="#D9D9D9",
    highlightthickness=0,
    command=lambda: window.destroy(),
    relief="flat",
)
button_6.place(
    x=940.0798950195312,
    y=2.0,
    width=30.08994483947754,
    height=30.08994483947754
)

button_image_hover_6 = PhotoImage(
    file=relative_to_assets("button_hover_6.png"))

def button_6_hover(e):
    button_6.config(
        image=button_image_hover_6
    )
def button_6_leave(e):
    button_6.config(
        image=button_image_6
    )

button_6.bind('<Enter>', button_6_hover)
button_6.bind('<Leave>', button_6_leave)


button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,        activebackground="#D9D9D9",

    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=904.0,
    y=2.0,
    width=30.0,
    height=30.146074295043945
)

button_image_hover_7 = PhotoImage(
    file=relative_to_assets("button_hover_7.png"))

def button_7_hover(e):
    button_7.config(
        image=button_image_hover_7
    )
def button_7_leave(e):
    button_7.config(
        image=button_image_7
    )

button_7.bind('<Enter>', button_7_hover)
button_7.bind('<Leave>', button_7_leave)
class WindowDrag:
    def __init__(self, root, drag_widget):
        self.root = root
        self.drag_widget = drag_widget
        self.drag_widget.bind("<ButtonPress-1>", self.start_drag)
        self.drag_widget.bind("<B1-Motion>", self.do_drag)
        self.start_x = 0
        self.start_y = 0

    def start_drag(self, event):
        self.start_x = event.x_root
        self.start_y = event.y_root

    def do_drag(self, event):
        deltax = event.x_root - self.start_x
        deltay = event.y_root - self.start_y
        x = self.root.winfo_x() + deltax
        y = self.root.winfo_y() + deltay
        self.root.geometry(f"+{x}+{y}")
        self.start_x = event.x_root
        self.start_y = event.y_root

        # Center window
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
window.geometry(f"980x653+{(screen_width-980)//2}+{(screen_height-653)//2}")
window.overrideredirect(True)  # Remove titlebar
# Add this after: canvas.create_rectangle(0.0, 0.0, 980.0, 35.0, ...)
WindowDrag(window, canvas)  # Bind dragging to top bar


window.resizable(False, False)
window.mainloop()
